export default {
    softskillTags : [
      { name: "Communication" },
      { name: "Leadership" },
      { name: "Teamwork" },
      { name: "Project Management" },
      { name: "Creativity" },
      { name: "Positive Attitude" },
      { name: "Decision Making" },
      { name: "Problem Solving" },
      { name: "Time Management" },
   ],
    programmingTags : [
      { icon: "logos:python", name: "Python", link: "https://www.python.org/" },
      { icon: "skill-icons:javascript", name: "JavaScript", iconSize: "20", link: "https://www.w3schools.com/js/" },
      { icon: "skill-icons:typescript", name: "TypeScript", iconSize: "20", link: "https://www.typescriptlang.org/" },
      { icon: "skill-icons:golang", name: "Golang", link: "https://go.dev/" },
      { icon: "skill-icons:c", name: "C", link: "https://www.w3schools.com/c/c_intro.php" },
      { icon: "skill-icons:cpp", name: "C++", link: "https://www.w3schools.com/cpp/" },
      { icon: "skill-icons:cs", name: "C#", link: "https://www.w3schools.com/cs/index.php" },
   ],
    frontendTags : [
      { icon: "vscode-icons:file-type-html", name: "HTML", link: 'https://www.w3schools.com/html/' },
      { icon: "vscode-icons:file-type-css", name: "CSS", link: "https://www.w3schools.com/css/" },
      { icon: "skill-icons:javascript", name: "JavaScript", iconSize: "20", link: "https://www.w3schools.com/js/" },
      { icon: "skill-icons:typescript", name: "TypeScript", iconSize: "20", link: "https://www.typescriptlang.org/" },
      { icon: "vscode-icons:file-type-vue", name: "Vue.js", link: "https://vuejs.org/" },
      { icon: "logos:nuxt-icon", name: "Nuxt.js", link: "https://nuxtjs.org/" },
      { icon: "skill-icons:react-dark", name: "React", link: "https://react.dev/" },
      { icon: "logos:tailwindcss-icon", name: "TailwindCSS", link: "https://tailwindcss.com/" },
      { icon: "skill-icons:bootstrap", name: "Bootstrap", link: "https://getbootstrap.com/" },
      { icon: "skill-icons:materialui-dark", name: "MUI", link: "https://mui.com/" },
   ],
    backendTags : [
      { icon: "skill-icons:javascript", name: "JavaScript", iconSize: "20", link: "https://www.w3schools.com/js/" },
      { icon: "skill-icons:golang", name: "Golang", link: "https://go.dev/" },
      { icon: "vscode-icons:file-type-appscript", name: "App Script", link: "https://www.google.com/script/start/" },
      { icon: "bi:filetype-sql", name: "SQL", iconSize: "20", link: "https://www.w3schools.com/sql/" }
   ],
    serviceTags : [
      { icon: "line-md:github-loop", name: "Git", link: "https://git-scm.com/" },
      { icon: "skill-icons:docker", name: "Docker", link: "https://www.docker.com/" },
      { icon: "logos:postgresql", name: "PostgreSQL", link: "https://www.postgresql.org/" },
      { icon: "vscode-icons:file-type-netlify", name: "Netlify", link: "https://www.netlify.com/" },
      { icon: "skill-icons:kubernetes", name: "Kubernetes", link: "https://kubernetes.io/" },
      { icon: "vscode-icons:file-type-swagger", name: "Swagger", link: "https://swagger.io/" },
   ],
    toolTags : [
      { icon: "logos:visual-studio-code", name: "VS Code", link: "https://code.visualstudio.com/" },
      { icon: "line-md:github-loop", name: "Github", link: "https://github.com/" },
      { icon: "skill-icons:postman", name: "Postman", link: "https://www.postman.com/downloads/" },
      { icon: "logos:slack-icon", name: "Slack", link: "https://slack.com/" },
      { icon: "vscode-icons:file-type-bitbucketpipeline", name: "Bitbucket", link: "https://bitbucket.org/" },
      { icon: "devicon:jira", name: "Jira", link: "https://jira.atlassian.com/" },
      { icon: "devicon:jenkins", name: "Jenkins", link: "https://www.jenkins.io/" },
      { icon: "logos:openshift", name: "OpenShift", link: "https://www.redhat.com/en/technologies/cloud-computing/openshift" },
      { icon: "logos:datagrip", name: "DataGrip", link: "https://www.jetbrains.com/datagrip/" },
      { icon: "simple-icons:googlesheets", name: "Google Sheet", link: "https://www.google.com/intl/th_th/sheets/about/" },
      { icon: "logos:figma", name: "Figma", link: "https://www.figma.com/" },
      { icon: "logos:trello", name: "Trello", link: "https://trello.com/th" },
   ],
}
